package signin;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
// Generated by Selenium IDE
import driver.Watcher;
import driver.ClientDriver;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class Signin {

    String testCaseId;
    String testRunId = "62";//Signin -Automated test cases
    @Rule
    public Watcher watcher = new Watcher(ClientDriver.driver);

    @BeforeClass
    public static void delay() {
        try {
            Thread.sleep(10000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Signin.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("SigninLayout Delay 10 seconds applied ");
    }

    @Test
    public void testlogin() {
        System.out.println("Start sign in");
        ClientDriver.base.getElementByXpath("//*[@contentDescription='تسجيل الدخول']").click();
        ClientDriver.base.getElementByXpath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.widget.ImageView[1]").click();
        ClientDriver.driver.getKeyboard().sendKeys("0599741147");
        ClientDriver.base.getElementByXpath("//*[@class='android.widget.EditText']").click();
        ClientDriver.driver.getKeyboard().sendKeys("1234567");
        ClientDriver.base.getElementByXpath("//*[@contentDescription='تسجيل الدخول' and @class='android.widget.Button']").click();
        ClientDriver.base.getElementByXpath("//*[@contentDescription='مستعد للجولة التعريفية؟']").click();
        ClientDriver.base.getElementByXpath("//*[@contentDescription='تجاهل']").click();
        ClientDriver.base.getElementByXpath("//*[contains(@contentDescription,'الرئيسية')]").click();
        ClientDriver.base.getElementByXpath("//*[@contentDescription='أهلاً بك']").click();
        ClientDriver.base.Wait(5);
//        new WebDriverWait(driver, 10).until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@contentDescription='aseel']")));
        ClientDriver.base.getElementByXpath("//*[@contentDescription='aseel']").click();
        System.out.println("End sign in");
    }

}
