package signin;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
// Generated by Selenium IDE
import driver.ClientDriver;
import driver.Watcher;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runners.MethodSorters;
import org.openqa.selenium.By;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class Signin {

    String testCaseId;
    String testRunId = "62";//Signin -Automated test cases
    @Rule
    public Watcher watcher = new Watcher(ClientDriver.driver);

    @BeforeClass
    public static void delay() {
        try {
            Thread.sleep(10000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Signin.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("SigninLayout Delay 10 seconds applied ");
    }

    @Test
    public void testsingin() {
        String mobileelementXpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.widget.ImageView[1]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(mobileelementXpath));
        ClientDriver.base.getElementByXpath(mobileelementXpath).click();
        ClientDriver.driver.getKeyboard().sendKeys("0599741147");
        String passwordelementXpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.widget.ImageView[2]";
        ClientDriver.base.getElementByXpath(passwordelementXpath).click();
        ClientDriver.driver.getKeyboard().sendKeys("1234567");
        String singinButtonXpath = "//android.widget.Button[@content-desc=\"تسجيل الدخول\"]";
        ClientDriver.base.getElementByXpath(singinButtonXpath).click();
        String WelcomeTextXpath = "//android.view.View[@content-desc=\"أهلاً بك\"]";
        String NameOfClientXpath = "//android.view.View[@content-desc=\"AM\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(WelcomeTextXpath));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(NameOfClientXpath));
    }
}
