package signin;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
// Generated by Selenium IDE
import driver.ClientDriver;
import driver.Watcher;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runners.MethodSorters;
import org.openqa.selenium.By;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class Signin {

    String testCaseId;
    String testRunId = "62";//Signin -Automated test cases
    @Rule
    public Watcher watcher = new Watcher(ClientDriver.driver);

    @BeforeClass
    public static void delay() {
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Signin.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("SigninLayout Delay 1 second applied ");
    }

    @Test
    public void test1_singin() {
        String mobileelementXpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.widget.ImageView[1]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(mobileelementXpath));
        ClientDriver.base.getElementByXpath(mobileelementXpath).click();
        ClientDriver.driver.getKeyboard().sendKeys("0599741147");
        String passwordelementXpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.widget.ImageView[2]";
        ClientDriver.base.getElementByXpath(passwordelementXpath).click();
        ClientDriver.driver.getKeyboard().sendKeys("1234567");
        String singinButtonXpath = "//android.widget.Button[@content-desc=\"تسجيل الدخول\"]";
        ClientDriver.base.getElementByXpath(singinButtonXpath).click();

    }

    @Test
    public void test2_welcomeScreen() {
        String tourXpath = "//android.view.View[@content-desc=\"مستعد للجولة التعريفية؟\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(tourXpath));
        String IgnoreButtonXpath = "//android.widget.Button[@content-desc=\"تجاهل\"]";
        ClientDriver.base.getElementByXpath(IgnoreButtonXpath).click();
    }

    @Test
    public void test3_homeScreen() {
        //        String WelcomeTextXpath = "//android.view.View[@content-desc=\"أهلاً بك\"]";
//        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(WelcomeTextXpath));
        String NameOfClientXpath = "//android.view.View[@content-desc=\"aseel\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(NameOfClientXpath));
    }
}
