package signin;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
// Generated by Selenium IDE
import driver.ClientDriver;
import driver.Watcher;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runners.MethodSorters;
import org.openqa.selenium.By;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class Welcome {

    String testCaseId;
    String testRunId = "62";//Signin -Automated test cases
    @Rule
    public Watcher watcher = new Watcher(ClientDriver.driver);

    @BeforeClass
    public static void delay() {
        try {
            Thread.sleep(10000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Signin.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("SigninLayout Delay 10 seconds applied ");
    }

    @Test
    public void testwelcome() {
        String loginButtonXpath = "//android.widget.Button[@content-desc=\"تسجيل الدخول\"]";
        System.out.println("Start sign in");
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(loginButtonXpath));
        ClientDriver.base.getElementByXpath(loginButtonXpath).click();
        String singupButtonXpath = "//android.widget.Button[@content-desc=\"حساب جديد\"]";
        System.out.println("Start sign up");
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(singupButtonXpath));
        // ClientDriver.base.getElementByXpath(singupButtonXpath).click();
        System.out.println("Welcome");
    }
}
