

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
// Generated by Selenium IDE
import driver.ClientDriver;
import logout.Logout;
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.MethodSorters;
import org.junit.runners.Suite;
import signin.Signin;
import signin.Welcome;

/**
 *
 * @author HP
 */
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
@RunWith(Suite.class)
@Suite.SuiteClasses({
    ClientDriver.class,
    Welcome.class,
    Signin.class,
    Logout.class,
    Quit.class,})

public class MvnTest {

    @Test
    public void mainTest() {
        System.out.println("MvnTest Famcare is Started ..");
    }

}
